from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models import User, Track
from app.schemas import ProjectRead
from app.auth import get_current_user
from app.services.audio_generation import generate_instrumental, generate_vocal_song
from app.services.storage import upload_audio_file
from app.routers.projects import _get_owned_project, _project_to_read

router = APIRouter(prefix="/projects", tags=["Audio Generation"])


class SongAudioRequest(BaseModel):
    style: Optional[str] = None


class InstrumentalRequest(BaseModel):
    prompt: str
    duration_seconds: int = 30


@router.post("/{project_id}/generate/song-audio", response_model=ProjectRead)
async def generate_song_audio(
    project_id: str,
    payload: SongAudioRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Renders an actual sung track for this project via ElevenLabs Music,
    using the lyrics already generated by /generate/lyrics or /generate/concept.
    """
    project = await _get_owned_project(project_id, db, current_user)
    if not project.lyrics or not project.lyrics.strip():
        raise HTTPException(status_code=422, detail="Generate lyrics for this project first.")

    audio_bytes = await generate_vocal_song(project.lyrics, payload.style)
    key, _ = await upload_audio_file(
        current_user.id, f"{project.id}-song.mp3", "audio/mpeg", audio_bytes
    )

    existing = next((t for t in project.tracks if t.track_type == "vocals_ai"), None)
    if existing:
        existing.file_url = key
    else:
        db.add(Track(project_id=project.id, name="AI Song", track_type="vocals_ai", file_url=key))

    await db.commit()
    await db.refresh(project, attribute_names=["tracks"])
    return _project_to_read(project)


@router.post("/{project_id}/generate/instrumental", response_model=ProjectRead)
async def generate_instrumental_audio(
    project_id: str,
    payload: InstrumentalRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Renders an instrumental-only track (no vocals) via Stability AI's Stable Audio."""
    project = await _get_owned_project(project_id, db, current_user)

    audio_bytes = await generate_instrumental(payload.prompt, payload.duration_seconds)
    key, _ = await upload_audio_file(
        current_user.id, f"{project.id}-instrumental.wav", "audio/wav", audio_bytes
    )

    existing = next((t for t in project.tracks if t.track_type == "instrumental_ai"), None)
    if existing:
        existing.file_url = key
    else:
        db.add(
            Track(
                project_id=project.id,
                name="AI Instrumental",
                track_type="instrumental_ai",
                file_url=key,
            )
        )

    await db.commit()
    await db.refresh(project, attribute_names=["tracks"])
    return _project_to_read(project)
